### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by AceDashDog** [JulianOzelRose/TRR-SaveMaster#4]
![image](https://github.com/JulianOzelRose/TRR-SaveMaster/assets/39329249/c44a3599-3aad-43c3-a858-6d88b36a7315)

I get "this app can't run on your pc" 
I'm running Windows 10 x64 Pro

Downloaded twice and same results

**Comment by JulianOzelRose** [comment]
It should run fine on Windows 10 x64, that's the system I'm using. I think that error has to do with Microsoft SmartScreen, because the .exe is not digitally signed. Make sure you are using an administrator account when you run it. If the error message still persists, try following the "Disable SmartScreen" instructions on [this link](https://www.addictivetips.com/windows-tips/fix-this-app-cant-run-on-your-pc-error-in-windows-10/). Hopefully that works.

**Comment by AceDashDog** [comment]
Smartscreen was already off, and I am an administrator. If I try and run it from the elevated command line I get "Unsupported 16-bit application". Very odd!

**Comment by JulianOzelRose** [comment]
Ah, I think I see the issue now. It isn't downloading properly, even though you downloaded it twice. Your browser might be blocking unsigned .exe downloads. I can tell because in your screenshot there is no icon for the .exe, it should look like this:

![Capture](https://github.com/JulianOzelRose/TRR-SaveMaster/assets/95890436/d06b470c-305d-4525-9e6e-0a8a3145b2aa)

Try this, download this .zip archive, then extract it and run the .exe -- here's the archive:

[TRR-SaveMaster.zip](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14380487/TRR-SaveMaster.zip)

If that still doesn't do it, your browser might still be blocking archived .exe files, in which case, download this file, then just rename the extension from .txt to .exe:

[TRR-SaveMaster.txt](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14380493/TRR-SaveMaster.txt)

Let me know if any of that works.

**Comment by AceDashDog** [comment]
That's got it - thanks! 


 

--



Hugh Foster 

***@***.***

http://www.ace-dog.com 

A picture is worth a 1000 words but it uses up a 1000 times the memory.

--



Friday, February 23, 2024, 12:00:42 AM, you wrote:

**Comment by JulianOzelRose** [comment]
No problem, glad it worked. I've re-attached the latest version as both archive and .txt, it has some pretty good improvements. Marking this issue as closed. Feel free to open another if you come across one. Enjoy.

[TRR-SaveMaster.txt](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14397104/TRR-SaveMaster.txt)
[TRR-SaveMaster.zip](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14397105/TRR-SaveMaster.zip)
