### ISSUE TITLE
Changes doesn't apply

### ISSUE THREAD

**Issue by Menghus** [JulianOzelRose/TRR-SaveMaster#7]
Hello!

I've tried to apply changes I made to ammo and adding a weapon for a save file I have in TR3 but when I load the save file that I edited, no changes are made and I still have the same amount of ammo and stuff I had before editing the save file. Why is this happening and what's the solution?

**Comment by JulianOzelRose** [comment]
Hi,

I know this sounds super basic, but have you tried restarting the game? Since the game caches the savegame file into memory, you have to restart it before the changes take effect. If the changes still aren't applying, you might want to try disabling cloud saves. You can do this through Steam by right-clicking on TR I-III Remastered then going to Properties, then unchecking the "Keep games saves in the Steam Cloud" option.

Let me know if any of that works.

**Comment by Menghus** [comment]
It seems like this problem only occurs in some save slots and not every one. I don't know what triggers this problem, maybe the specific save slot that I was trying to edit is corrupted or something because I tried editing other save slots and it worked. I'll let you know if I discover something more.

**Comment by JulianOzelRose** [comment]
If you send me the savegame file and tell me which slots aren't saving properly (and what changes you are trying to apply) I will have a look at it.

**Comment by Menghus** [comment]
Nevermind, I solved the problem by overwriting the corrupted save slot with another save slot that was working properly.

**Comment by Menghus** [comment]
Btw, I would like to ask you if you possibly could make a mod that makes it possible to change enemy HP and/or weapon damage? Like an editor for all three games or something similar to the save editor.

**Comment by JulianOzelRose** [comment]
Glad it worked! I am finishing up a position editing feature for this program. When I'm done with that, I'll look into adding the ability to edit global variables like weapon damage and whatnot. Assuming those variables are stored in the savegame file (I think they are) then I would just integrate it into this editor.
