### ISSUE TITLE
[Feature Request] Ability to delete and move save slots

### ISSUE THREAD

**Issue by DonelBueno** [JulianOzelRose/TRR-SaveMaster#8]
Hey, first of all, thanks for the great editor =)

Can you add an option to delete and move save slots? This honestly should be in the game to begin with =/

**Comment by JulianOzelRose** [comment]
Hello and thank you :)

Yeah I agree, since they changed the savegame format from multiple files to just a single file, there should be some way to manage them. Someone else also asked if I could add this feature.

You can give this build a try:  [TRR-SaveMaster-SlotEdit-Build.zip](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14644662/TRR-SaveMaster-SlotEdit-Build.zip)

Just go to Edit -> Slots. Technically it's not deleting them, but you can hide them so that the game won't display them anymore... which also gives you the option to unhide them later. It doesn't disable entire the slot, just the savegame. So saving over it will make that slot visible again. Just click Refresh in the editor so it won't display the hidden savegames.

Moving the slots around is a bit trickier, not from a programming standpoint, but more like from a UX design standpoint. I'm not really a UX design guy. I'll think about how to implement that in a WinForms-friendly way. Not sure if it's exactly what you're looking for, but you might want to check out my [Savegame Extractor](https://github.com/JulianOzelRose/TombExtract). You can transfer individual savegames from one file to another, which makes downloading savegames from the Internet easier.

**Comment by DonelBueno** [comment]
Thanks for the answer.

Hiding slots work, but as you said, it's not the same as deleting. Thanks for that anyway, it stops the game from showing it, so it's fine.

About moving slots, you could make it look like a mod manager for games like Skyrim, where there is a list with all the slots, an arrow to move it up, an arrow to move it down and arrows to move it to the top or to the bottom. The most radical change compared to your current design would be to show all the slots on an open list instead of a dropdown menu.

EDIT: Maybe I was not clear, I want an option to move the slot sorting, so for example:

Slot 1: save 34
Slot 2: save 45

I would like to be able to exchange slot 1 and slot 2 positions.

**Comment by JulianOzelRose** [comment]
I see. I think this is probably more appropriate for my [TombExtract](https://github.com/JulianOzelRose/TombExtract) program, which is basically a savegame manager. Here's a primitive build that you can try out -- it can delete and reorder savegames:

[TombExtract.zip](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14676025/TombExtract.zip)

It only works for TR1 at the moment, and I haven't added error handling yet, so be sure to backup your savegame file. Just open the savegame file you want to reorder as the destination file, then click 'Manage Slots'. It should be very intuitive from there. If you're reordering a bunch of savegames, it might take a minute or two. Deleting should be pretty quick, it zeros the bytes so it's like it was never there.

If that works well for you, I will get it working for all 3 games, get a progress display, add error handling, etc. Let me know how it works.

**Comment by DonelBueno** [comment]
It worked perfectly, thank you!

I just had to disable Windows Defender before deleting save slots because the antimalware algorithm would make it take too long, as if the program stopped responding. Other than that, it was pretty easy and quick.

**Comment by JulianOzelRose** [comment]
The version I sent you renders the UI and does the deletion/reordering in the same thread. That's why the UI freezes up. Here's a new build you can try out:

[TombExtract.zip](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14712022/TombExtract.zip)

This one should work for all 3 games. It runs on separate threads so the UI shouldn't lock up anymore, and there's a progress display. Let me know how that one works. If it works well, I'll update the TombExtract repo to have this feature.

**Comment by DonelBueno** [comment]
Tested here. The UI indeed doesn't freeze while deleting the save, although it still takes a long time with WIndows Defender enabled.

Bugs I've noticed:

-  I couldn't see any progress bar when deleting slots.
- TR2 shows the slots correctly on the main software window upon first opening it, but when clicking on "Manage slots", only the number of slots equal to the number of saves you have on TR1 are shown (19 in my case).
- When I click on "Manage slots" for TR2 or TR3, then close the new window, the slots list on the main window become the one from TR1.

![image](https://github.com/JulianOzelRose/TRR-SaveMaster/assets/4239694/b65aef3e-a80c-4b55-814c-0c6fcb419652)

**Comment by JulianOzelRose** [comment]
I noticed I mixed up a few function calls after I sent you that build. Try this one:

[TombExtract.zip](https://github.com/JulianOzelRose/TRR-SaveMaster/files/14719585/TombExtract.zip)

Should address everything you listed except the deletion progress bar. I didn't add one because it should be pretty quick to zero the savegame bytes. But if it takes a while on your system, I will add one.

**Comment by DonelBueno** [comment]
Great work, now everything works correctly!

About the progress bar, my system is not weak (Ryzen 5800x, 32 GB RAM @ 3600 MHz CL14), it takes 1 second when Windows Defender is disabled, but 30-40 seconds when it is enabled. It's a specific case, so I don't think the progress bar is necessary.

Just a request: can you default the first folder when clicking on "Source file" or "Destination file" to the same folder your program .exe is in? Or allow drag and drop of the save file.
